package menu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import music.MusicPlayer;

//This is a GUI
public class GameplayMenu extends javax.swing.JPanel {

	boolean musicPlaying = true;

	private MusicPlayer music = new MusicPlayer();
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public GameplayMenu() {
		initComponents();
		music.playSound("MusicFiles/sound.wav");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">

	private void initComponents() {

		/**
		 * This method is called from within the constructor to initialize the
		 * form. WARNING: Do NOT modify this code. The content of this method is
		 * always regenerated by the Form Editor.
		 */

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setPreferredSize(new java.awt.Dimension(900, 720));

		setLayout(null);

		jButton1.setText("Mute");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (musicPlaying == true) {
					music.muteSound();
					musicPlaying = false;
				} else {
					music.playSound("MusicFiles/sound.wav");
					musicPlaying = true;
				}
			}
		});
		add(jButton1);

		jButton1.setBounds(670, 50, 61, 25);

		jLabel1.setIcon(new javax.swing.ImageIcon("ImageFiles/cover.jpg"));
		jLabel1.setMaximumSize(new java.awt.Dimension(900, 720));
		jLabel1.setMinimumSize(new java.awt.Dimension(900, 720));
		add(jLabel1);
		jLabel1.setBounds(0, 0, 920, 720);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration
}
