package quiz;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

import menu.LoadFont;

public class NameAndGenderPanel extends javax.swing.JPanel {

	public final JButton enterNameButton = new JButton("Enter");
	public final JTextField firstName = new JTextField();
	public final JTextField lastName = new JTextField();
	private JLabel mainMenuImage = new JLabel();

	private static final long serialVersionUID = 1L;

	// Starts new form for page
	public NameAndGenderPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		setPreferredSize(new java.awt.Dimension(900, 720));
		setLayout(null);
		
		String[] options = { "Male", "Female" };
		@SuppressWarnings({ "rawtypes", "unchecked" })
		JComboBox comboBox = new JComboBox(options);
		comboBox.setBounds(150, 270, 60, 50);

		LoadFont walkway = new LoadFont();
		enterNameButton.setOpaque(false);
		enterNameButton.setContentAreaFilled(false);
		enterNameButton.setBorderPainted(false);
		enterNameButton.setFont(walkway.callFont("FontFiles/walkway.ttf").deriveFont(1, 24));
		enterNameButton.setBounds(150, 320, 680, 50);
		enterNameButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		enterNameButton.setForeground(new java.awt.Color(255, 0, 0));

		JLabel title = new JLabel("Before we get started with the game please");
		title.setFont(walkway.callFont("FontFiles/walkway.ttf").deriveFont(2, 40));
		title.setForeground(new java.awt.Color(255, 0, 0));
		title.setBounds(150, 30, 680, 50);

		JLabel title1 = new JLabel("Before we get started with the game please");
		title1.setFont(walkway.callFont("FontFiles/walkway.ttf").deriveFont(2, 40));
		title1.setForeground(new java.awt.Color(255, 0, 0));
		title1.setBounds(150, 200, 680, 50);

		JLabel title2 = new JLabel("enter the following information.");
		title2.setFont(walkway.callFont("FontFiles/walkway.ttf").deriveFont(2, 40));
		title2.setForeground(new java.awt.Color(255, 0, 0));
		title2.setBounds(150, 230, 680, 50);
		
		firstName.setBounds(150, 390, 680, 50);
		lastName.setBounds(150, 500, 680, 50);
		

		add(title);
		add(title1);
		add(title2);
		add(enterNameButton);
		add(comboBox);
		add(firstName);
		add(lastName);

		// add image
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Image scaledImage = toolkit.getImage("ImageFiles/cover.jpg");
		ImageIcon image = new ImageIcon(scaledImage.getScaledInstance(900, 720, Image.SCALE_DEFAULT));
		mainMenuImage.setIcon(image);

		add(mainMenuImage);
		mainMenuImage.setBounds(0, 0, 900, 720);

	}

}
