package quiz;

import javax.swing.JComboBox;
import javax.swing.JPanel;

public class QuizPanel extends JPanel {

	private static final long serialVersionUID = -889635768481445731L;

		private javax.swing.JComboBox<String> jComboBox1;
	    private javax.swing.JComboBox<String> jComboBox2;
	    private javax.swing.JComboBox<String> jComboBox3;
	    private javax.swing.JComboBox<String> jComboBox4;
	    private javax.swing.JComboBox<String> jComboBox5;
	    private javax.swing.JScrollBar jScrollBar1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JScrollPane jScrollPane3;
	    private javax.swing.JScrollPane jScrollPane4;
	    private javax.swing.JScrollPane jScrollPane5;
	    private javax.swing.JTextArea jTextArea1;
	    private javax.swing.JTextArea jTextArea2;
	    private javax.swing.JTextArea jTextArea3;
	    private javax.swing.JTextArea jTextArea4;
	    private javax.swing.JTextArea jTextArea5;
	
	public QuizPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                      
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jComboBox4 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(900, 720));
        setRequestFocusEnabled(false);
        setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(jComboBox1);
        jComboBox1.setBounds(810, 570, 40, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 150, 730, 130);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        add(jScrollPane2);
        jScrollPane2.setBounds(60, 570, 730, 130);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(jComboBox2);
        jComboBox2.setBounds(810, 10, 40, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(jComboBox3);
        jComboBox3.setBounds(810, 150, 40, 22);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3);
        jScrollPane3.setBounds(60, 10, 730, 130);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setEditable(false);
        jScrollPane4.setViewportView(jTextArea4);

        add(jScrollPane4);
        jScrollPane4.setBounds(60, 290, 730, 130);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(jComboBox5);
        jComboBox5.setBounds(810, 290, 40, 22);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        add(jScrollPane5);
        jScrollPane5.setBounds(60, 430, 730, 130);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        add(jComboBox4);
        jComboBox4.setBounds(810, 430, 40, 22);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
  
	/*
	String getFirstNameText = firstName.getText();
	String getLastNameText = lastName.getText();
	if (getFirstNameText.isEmpty() || getFirstNameText.equals(null) || getLastNameText.isEmpty()
			|| getLastNameText.equals(null) || getFirstNameText.contains(" ")
			|| getLastNameText.contains(" ")) {
		myOutput.setText("Invalid Name Provided. Please try again!");
		add(initialButtonPanel);
	} else {
		main.setFirstName(getFirstNameText);
		main.setLastName(getLastNameText);
		if (comboBox.getSelectedItem().equals("Male")) {
			main.isFemale(false);
		}
		QuizQuestions quiz1 = (QuizQuestions) quiz.getCharacterQuiz().get(0);
		String question1 = quiz1.getQuestionText();
		String answer1 = quiz1.getAnswerOptions().get("1");
		String answer2 = quiz1.getAnswerOptions().get("2");
		String answer3 = quiz1.getAnswerOptions().get("3");
		String answer4 = quiz1.getAnswerOptions().get("4");
		QuizQuestions quiz2 = (QuizQuestions) quiz.getCharacterQuiz().get(1);
		String question2 = quiz2.getQuestionText();
		String answer21 = quiz2.getAnswerOptions().get("1");
		String answer22 = quiz2.getAnswerOptions().get("2");
		String answer23 = quiz2.getAnswerOptions().get("3");
		String answer24 = quiz2.getAnswerOptions().get("4");
		QuizQuestions quiz3 = (QuizQuestions) quiz.getCharacterQuiz().get(2);
		String question3 = quiz3.getQuestionText();
		String answer31 = quiz3.getAnswerOptions().get("1");
		String answer32 = quiz3.getAnswerOptions().get("2");
		String answer33 = quiz3.getAnswerOptions().get("3");
		String answer34 = quiz3.getAnswerOptions().get("4");
		QuizQuestions quiz4 = (QuizQuestions) quiz.getCharacterQuiz().get(3);
		String question4 = quiz4.getQuestionText();
		String answer41 = quiz4.getAnswerOptions().get("1");
		String answer42 = quiz4.getAnswerOptions().get("2");
		String answer43 = quiz4.getAnswerOptions().get("3");
		String answer44 = quiz4.getAnswerOptions().get("4");
		QuizQuestions quiz5 = (QuizQuestions) quiz.getCharacterQuiz().get(4);
		String question5 = quiz5.getQuestionText();
		String answer51 = quiz5.getAnswerOptions().get("1");
		String answer52 = quiz5.getAnswerOptions().get("2");
		String answer53 = quiz5.getAnswerOptions().get("3");
		String answer54 = quiz5.getAnswerOptions().get("4");
		myOutput.setText("<html>" + question1 + "<br/>1: " + answer1 + "<br/>2: " + answer2 + "<br/>3: "
				+ answer3 + "<br/>4: " + answer4 + "</html>");
		String[] options = { "1", "2", "3", "4" };
		question1Box = new JComboBox(options);
		question2Box = new JComboBox(options);
		question3Box = new JComboBox(options);
		question4Box = new JComboBox(options);
		question5Box = new JComboBox(options);
		myOutput2.setText("<html>" + question2 + "<br/>1: " + answer21 + "<br/>2: " + answer22 + "<br/>3: "
				+ answer23 + "<br/>4: " + answer24 + "</html>");
		myOutput3.setText("<html>" + question3 + "<br/>1: " + answer31 + "<br/>2: " + answer32 + "<br/>3: "
				+ answer33 + "<br/>4: " + answer34 + "</html>");
		myOutput4.setText("<html>" + question4 + "<br/>1: " + answer41 + "<br/>2: " + answer42 + "<br/>3: "
				+ answer43 + "<br/>4: " + answer44 + "</html>");
		myOutput5.setText("<html>" + question5 + "<br/>1: " + answer51 + "<br/>2: " + answer52 + "<br/>3: "
				+ answer53 + "<br/>4: " + answer54 + "</html>");
				*/
		
	
}
