package game.resources;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.*;


public class MainMenuPanel extends javax.swing.JPanel{
	//Starts new form for page
	    public MainMenuPanel() {
	        initComponents();
	    }
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
// declare form
	    private void initComponents(){
	    setPreferredSize(new java.awt.Dimension(900, 720));
        setLayout(null);
	//buttons set to private must sit outside of panel definition.
	JButton continueButton = new JButton("Continue");
	JButton newGameButton = new JButton("New Game");
	JButton extrasButton = new JButton("Extras");
	JButton quitButton = new JButton("Exit");
	JLabel mainMenuImage = new JLabel();
	

	//add buttons to panel
			add(continueButton);
			add(newGameButton);
			add(extrasButton);
			add(quitButton);
	//style buttons
	LoadFont walkway = new LoadFont();

			
			continueButton.setOpaque(false);
			continueButton.setContentAreaFilled(false);
			continueButton.setBorderPainted(false);
			continueButton.setFont(walkway.callFont().deriveFont(1, 34));
			continueButton.setBounds(10, 420, 180, 50);
			continueButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			continueButton.setForeground(new java.awt.Color(255, 255, 255));
			newGameButton.setOpaque(false);
			newGameButton.setContentAreaFilled(false);
			newGameButton.setBorderPainted(false);
			newGameButton.setFont(walkway.callFont().deriveFont(1, 34));
			newGameButton.setBounds(10, 480, 400, 50);
			newGameButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			newGameButton.setForeground(new java.awt.Color(255, 255, 255));
			extrasButton.setOpaque(false);
		    extrasButton.setContentAreaFilled(false);
			extrasButton.setBorderPainted(false);
			extrasButton.setFont(walkway.callFont().deriveFont(1, 34));
			extrasButton.setBounds(10, 540, 160, 50);
			extrasButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			extrasButton.setForeground(new java.awt.Color(255, 255, 255));
			quitButton.setOpaque(false);
			quitButton.setContentAreaFilled(false);
			quitButton.setBorderPainted(false);
			quitButton.setFont(walkway.callFont().deriveFont(1, 34));
			quitButton.setBounds(10, 600, 130, 50);
			quitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
			quitButton.setForeground(new java.awt.Color(255, 255, 255));
	//add image
			 mainMenuImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Howl\\Pictures\\the_alchemist__self_transmutation_by_hypnothalamus-d8149c0.jpg")); 
		        add(mainMenuImage);
		        mainMenuImage.setBounds(0, 0, 900, 720);
	
		}//form finish	

}//close class
